services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    secrets:
      - db_password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

secrets:
  db_password:
    file: db_password.txt